### ISSUE TITLE
unicode to Rance IV (zh-CN charset)

### ISSUE THREAD

**Issue by silas1037** [kichikuou/xsys35c#1]
language: zh-CN

descript: I follow manual of unicode, but it seems that some Chinese character outside SJIS charset range could not show. (eg. '啊' is not in sjis)

And I also get confused with following notes, where are these ttf, should I download from where, put into font folder or install? Maybe it don't effect and cause the problem.

```
To change the font in xsystem35, create a file named .xsys35rc in the game folder with the following contents (replace the file names):

ttfont_gothic: your-sans-serif-font.ttf
ttfont_mincho: your-serif-font.ttf
```

![image](https://user-images.githubusercontent.com/36977717/112753685-3600e380-900b-11eb-8e7f-7134078e506d.png)

**Comment by kichikuou** [comment]
The problem is that the default font of xsystem35-sdl2 doesn't have Chinese characters.

Try this:
1. Download unifont-13.0.06.ttf from [Unifoundry.com](http://unifoundry.com/unifont/index.html)
2. Put it in the game folder (where the `*.ALD` files are).
3. Create `.xsys35rc` file in the same folder, with the following contents:
```
ttfont_gothic: unifont-13.0.06.ttf
ttfont_mincho: unifont-13.0.06.ttf
```

Any .ttf and .otf fonts would work. If you are not satisfied with the quality of unifont, try [Source Han Sans](https://github.com/adobe-fonts/source-han-sans).

**Comment by silas1037** [comment]
hanny~ho, it works, thanks !

**Comment by silas1037** [comment]
It seems that xsys35dc don't support decode ald from unicode?

**Comment by kichikuou** [comment]
> It seems that xsys35dc don't support decoding ald from unicode?

It doesn't. 
Almost all existing files are in SJIS, so I thought it wasn't a big deal.
