### ISSUE TITLE
Inconsistent file naming

### ISSUE THREAD

**Issue by RottenBlock** [kichikuou/xsys35c#5]
Hi,

I was working with someone over the past week and a half who was having trouble with xsys35. We eventually boiled it down to two problems. First off, following the Basic Workflow section of the Readme produces odd results. If you run the decompiler as instructed, and then run the compiler with this step:

`xsys35c -p decompiled/xsys35c.cfg -o out.ALD -a out.ain`

The game doesn't produce a file called out.ALD, it produces a file called "out.ALDSA.ALD". Obviously this is not correct. Changing the line to read "-o out" instead of "-o out.ALD" will correct the problem as a temporary fix, but now the line is inconsistent between "-o" and "-a". I haven't looked at the code, but it seems like the program tried to append "SA.ALD" to the end of the file name incorrectly, and only when the user tries to use "-o out.ALD"?

---------------

The other problem doesn't seem to be xsys35's fault so I won't be filing it as a separate bug report, but I wanted you to know about it in case someone else comes asking about it. Basically, even though we eventually got a properly-compiled file, the game still wasn't running correctly. I suggested a few things and the step that seemed to work was renaming all the Japanese, ALD file names to English names. I was only talking to them via email, so I don't know exactly what happened. Maybe it was actually some other innocent mistake, but it's possible English Windows' notoriously poor Japanese character support was causing some kind of strange problem. Either way, I don't have enough information to work on this in isolation, but if it ever comes up again, I'd recommend you tell the user to swap to ASCII file names.

**Comment by kichikuou** [comment]
Thanks for the report!

Yes, the compiler appends `SA.ALD` because it may also generate ...SB.ALD, ...SC.ALD, etc. I [changed the meaning of `-o` option](https://github.com/kichikuou/xsys35c/commit/e5bbfdba03c51546df126a1fff0c97e17a68e942) long time ago and forgot to update the instructions.

In System3.9 games, AIN filename should always be `System39.ain`. So, if you want `fooSA.ALD` and `System39.ain`, the correct command line is:

```
xsys35c -p decompiled/xsys35c.cfg -o foo -a System39.ain
```

And thanks for the info about the filename issue. System39.exe is not internationalized so I can imagine non-ASCII characters will cause problems if the system locale is not set to Japanese. xsystem35 knows how to handle international characters so such problems should not occur. :)
